export default {
  LOAD_MESSAGES: 'LOAD_MESSAGES',
  MESSAGES_LOADED: 'MESSAGES_LOADED',
  LOAD_MESSAGE: 'LOAD_MESSAGE',
  MESSAGE_LOADED: 'MESSAGE_LOADED',

  SEND_MESSAGE: 'SEND_MESSAGE',
  MESSAGE_SENT: 'MESSAGE_SENT',

  CAPTURE_MESSAGE: 'CAPTURE_MESSAGE',
};
